Badges, sign in pages and profile modal window
IraKhomyk/Gamification pull request #17
Opened 2021-04-06 15:43 UTC by IraKhomyk

2021-04-13 17:00 UTC, ksarkisyan requested changes

2021-04-14 16:46 UTC, IraKhomyk commented on ProjectFrontEnd/src/app/app.component.html
> -    <app-header></app-header>
fixed

2021-04-14 16:46 UTC, IraKhomyk commented on ProjectFrontEnd/src/app/app.component.ts
> +  title = 'CMFCTN';
fixed

2021-04-14 16:46 UTC, IraKhomyk commented on ProjectFrontEnd/src/app/modules/dashboard/components/request-achievement/request-achievement.component.html
> +    <mat-select [(value)]="selectAchievement" id="achievement" formControlName="achievement" required>
fixed

2021-04-14 16:47 UTC, IraKhomyk commented on ProjectFrontEnd/src/app/shared/edit-profile/edit-profile-modal-win/edit-profile-modal-win.component.ts
> +  profileForm: FormGroup = new FormGroup({
fixed

2021-04-14 16:47 UTC, IraKhomyk commented on ProjectFrontEnd/src/app/shared/edit-profile/edit-profile-modal-win/edit-profile-modal-win.component.html
> +                <textarea matInput id="firstName" formControlName="firstName" required></textarea>
fixed

2021-04-14 16:47 UTC, IraKhomyk commented on ProjectFrontEnd/src/styles.scss
>  .request-model-container .mat-dialog-container {
fixed

2021-04-14 16:47 UTC, IraKhomyk commented on ProjectFrontEnd/src/index.html
> +  <title>Camification</title>
fixed

2021-04-18 16:46 UTC, ksarkisyan approved these changes

2021-04-22 08:54 UTC, merged